### ISSUE TITLE
Railway build fails on turbo run build step

### ISSUE THREAD

**Issue by dit7ya** [calcom/cal.com#1876]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Deployment on Railway fails with latest master with the following error (last few lines).

```
Installing CycloneDX Node.js Module 3.0.7
Completed in 270ms

  Configuring environment
    Appending CycloneDX Node.js Module onto PATH

  Running CycloneDX Node.js Module
    Running 'cyclonedx-bom -o bom.json'
Completed in 7.115s
Paketo Node Run Script Buildpack 0.3.1
  Executing build process
    Executing scripts
      Running 'yarn run build'
yarn run v1.22.17
        $ turbo run build
         WARNING  cannot find a .git folder. Falling back to manual file hashing (which may be slower). If you are running this build in a pruned directory, you can ignore this message. Otherwise, please initialize a git repository in the root of your monorepo
        • Packages in scope: @calcom/config, @calcom/docs, @calcom/lib, @calcom/prisma, @calcom/tsconfig, @calcom/types, @calcom/web
        • Running build in 7 packages
        @calcom/prisma:build: cache miss, executing 75c48866a38ef60f
        @calcom/docs:build: cache miss, executing 141ef901a14e36f9
        @calcom/prisma:build: $ yarn generate-schemas
        @calcom/docs:build: $ next build
        @calcom/prisma:build: $ prisma generate
        @calcom/docs:build: Attention: Next.js now collects completely anonymous telemetry regarding usage.
        @calcom/docs:build: This information is used to shape Next.js' roadmap and prioritize features.
        @calcom/docs:build: You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
        @calcom/docs:build: https://nextjs.org/telemetry
        @calcom/docs:build: 
        @calcom/docs:build: info  - Checking validity of types...
        @calcom/prisma:build: Prisma schema loaded from schema.prisma
        @calcom/docs:build: warn  - The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config
        @calcom/prisma:build: 
        @calcom/prisma:build: ✔ Generated Prisma Client (3.0.2) to ./../../../layers/paketo-buildpacks_yarn-install/modules/node_modules/@prisma/client in 1.48s
        @calcom/prisma:build: 
        @calcom/prisma:build: ✔ Generated Zod Schemas (0.5.4) to ./zod in 1.54s
        @calcom/prisma:build: You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
        @calcom/prisma:build: ```
        @calcom/prisma:build: import { PrismaClient } from '@prisma/client'
        @calcom/prisma:build: const prisma = new PrismaClient()
        @calcom/prisma:build: ```
        @calcom/web:build: cache miss, executing 31e252698158b010
        @calcom/web:build: $ next build
        @calcom/docs:build: 
        @calcom/docs:build: Failed to compile.
        @calcom/docs:build: 
        @calcom/docs:build: ./pages/_app.js
        @calcom/docs:build: 5:10  Error: Parsing error: This experimental syntax requires enabling one of the following parser plugin(s): 'jsx, flow, typescript'  prettier/prettier
        @calcom/docs:build: 
        @calcom/docs:build: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
        @calcom/docs:build: error Command failed with exit code 1.
        @calcom/docs:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
        @calcom/docs:build: Error: command finished with error: exit status 1
        error Command failed with exit code 1.
        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
exit status 1
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 51
```

### Steps to Reproduce

1. Pull the latest master
2. `railway up`

**Comment by sagivo** [comment]
same issue here.

**Comment by sagivo** [comment]
I was able to resolve it by changing `package.json` file: 
```js
"build": "turbo run build --scope=@calcom/web",
```

**Comment by dit7ya** [comment]
> I was able to resolve it by changing `package.json` file:
> 
> ```js
> "build": "turbo run build --scope=@calcom/web",
> ```

After trying this though the build succeeded the app is crashing with errors like this in the console.

```
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    NextJS 33
framework-d0c58e6258a9b4ca.js:1:82793

Error rendering page:  TypeError: e is undefined
    NextJS 9
main-ba67c93d3362cdc6.js:1:13901
```

**Comment by arthurdenner** [comment]
The `build` script is failing with this error even locally, we need to fix it. But fixing it may not be enough to get a successful deployment since we'd be building both the `web` and `docs` apps.

Is there a way to override the build command on Railway through configuration in the repository?

For example, to fix the deployment on Heroku, I added a Heroku-specific script to only build the `web` app. Same to start it, I had to override to only start the `web` app.

Reference: https://github.com/calcom/cal.com/pull/1834

**Comment by sagivo** [comment]
looks like this commit solved the compile error - https://github.com/calcom/cal.com/commit/2194b92fdf5f705f6faf47e0a6c0b648ba877859 
However, the site still doesn't render and I also get these errors - https://github.com/calcom/cal.com/issues/1876#issuecomment-1042646568

**Comment by PeerRich** [comment]
> looks like this commit solved the compile error - https://github.com/calcom/cal.com/commit/2194b92fdf5f705f6faf47e0a6c0b648ba877859 
> 
> However, the site still doesn't render and I also get these errors - https://github.com/calcom/cal.com/issues/1876#issuecomment-1042646568
> 
> 
> 
> Really strange that they push to main branch things that break the site so easily. 

we'll look into it. works on our end. 

btw the usage of main is not always compatible with every provider. we recommend using the tagged releases (v.1.3)

**Comment by zomars** [comment]
IIRC this is already solved. Also add @PeerRich said We would recommend to wait for the official bi-weekly releases to update your self hosted instances. You really shouldn't be using every single update to main.

**Comment by sagivo** [comment]
@PeerRich, @zomars I disagree. `main` branch should always be working. If you want to experiment with different features you should open other branches for that. There's a need to always have an available, working, up-to-date version of your service and this is what `main` is made for. Tags/versions/releases are for milestones, not an indicator for availability.

**Comment by zomars** [comment]
> @PeerRich, @zomars I disagree. `main` branch should always be working. If you want to experiment with different features you should open other branches for that. There's a need to always have an available, working, up-to-date version of your service and this is what `main` is made for. Tags/versions/releases are for milestones, not an indicator for availability.

Agreed to disagree 🙏🏽

**Comment by PeerRich** [comment]
> @PeerRich, @zomars I disagree. `main` branch should always be working. If you want to experiment with different features you should open other branches for that. There's a need to always have an available, working, up-to-date version of your service and this is what `main` is made for. Tags/versions/releases are for milestones, not an indicator for availability. 

yes-ish. 

main works-- cal.com currently runs on it perfectly fine

but we won't postpone a merge into main just because railway or heroku may not work

thats what the tagged releases are for

also, we dont expect main to cause issues often, we just moved to turborepo last week which caused this (obviously the build flow needs to be adjusted for turborepo)

**Comment by dit7ya** [comment]
Ummm, I tried to deploy `main` on a separate environment on Railway but still getting the same errors as https://github.com/calcom/cal.com/issues/1876#issuecomment-1042646568. Then I tried deploying v1.3 and then got errors of https://github.com/calcom/cal.com/issues/1876#issue-1140306418.

**Comment by PeerRich** [comment]
> Ummm, I tried to deploy `main` on a separate environment on Railway but still getting the same errors as https://github.com/calcom/cal.com/issues/1876#issuecomment-1042646568. Then I tried deploying v1.3 and then got errors of https://github.com/calcom/cal.com/issues/1876#issue-1140306418.

i will contact the railways team

**Comment by PeerRich** [comment]
@zomars can you take care of this?

**Comment by PeerRich** [comment]
we will investigate. seems to be an issue unrelated to railway hence we will prioritize it higher. thank you all for reporting. 

main has the objective to be stable (it is on our end surprisingly)

just this week we moved to turborepo and this error is a one time side effect of that massive change

**Comment by zomars** [comment]
I'm deploying a new Railway instance from [my freshly forked repo](https://github.com/zomars/cal.com). Will update my findings here.

**Comment by zomars** [comment]
The original issue was fixed by #1887 BTW. Leaving it here for reference.

**Comment by zomars** [comment]
I've successfully deployed a new Railway instance, you can [try it yourself here](https://calendso-production-284a.up.railway.app). These are my findings:

- By default Railway tries to use Node v17 which is not supported by our project. I'll [open a PR](https://github.com/calcom/cal.com/pull/1977) to lock it to v14 from package json which Railway uses to determine the version to use.
- Generated a `JWT_SECRET` env variable using the `openssl rand -base64 24`
- Copied railway provided `DATABASE_URL` locally and ran `yarn prisma migrate deploy` from `packages/prisma` directory.
- Created my first user following the [README instructions](https://github.com/calcom/cal.com#setting-up-your-first-user).

**Comment by denik1981** [comment]
Thank you for this @zomars!

What did you find wrong with `node@16.x` (node LTS)?
I found the same issue with Railway due to Cal's `next-auth` dependency which is restricting the node engine to  `^14.15.0 || ^16.13.0`. An attempt to install with node@17 will fail as you mentioned but using `^14.15.0 || ^16.13.0` (intersection with next-auth) as Cal's node engine is working fine at my end.

**Comment by zomars** [comment]
> What did you find wrong with `node@16.x` (node LTS)? 

We haven't tested it yet.  We use since it's stable enough and it's Vercel's default.
