### ISSUE TITLE
Email conformation

### ISSUE THREAD

**Issue by leomalmachen** [calcom/cal.com#20116]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I dont get email conformations anymore when guests book trough the api v1 or v2 doesnt matter. The organizer gets a conformation mail but never the guests. 

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- What's happening right now that is different from what is expected

### Expected Results

- This is an ideal result that the system should get after the tests are performed

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

### Evidence

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

**Comment by Udit-takkar** [comment]
@leomalmachen this should be fixed

**Comment by leomalmachen** [comment]
Its still here for me I dont get a conformation as a Organizor and as Guest

**Comment by Udit-takkar** [comment]
@leomalmachen could you also please check spam folder and let me know your email?

**Comment by leomalmachen** [comment]
still happening - no mails in the spam - maybe it's due to new google mailinig permission? Email: leonhard.poeppel@malmachen.com

**Comment by leomalmachen** [comment]
@Udit-takkar i dont have the issue booking manually trough a website link - it's a issue that occures trough the api create booking - doenst matter if its v1 or v2

**Comment by CarinaWolli** [comment]
@JDP-Neo
