### ISSUE TITLE
The username shouldn't contain capital letters

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#2011]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The username may contain capital letters and that causes issues in user page, returning a 404 as it expects lowercase letters only.

**Comment by milospuac** [comment]
Thank you for reporting this! One of our engineers is on it.

**Comment by imkrunal** [comment]
This issue must be with existing users with capital letter in their name? I tried to update the username from settings and it automatically converted using `slugify`.

![image](https://user-images.githubusercontent.com/17720036/156145576-bb917aaf-bb83-400e-a9a2-fb6a4ffab1d7.png)

**Comment by alishaz-polymath** [comment]
This issue was through a 3rd party sign up. Closing it as this has already been fixed in Cal.

**Comment by LouisHaftmann** [comment]
> This issue was through a 3rd party sign up. Closing it as this has already been fixed in Cal.

where has this been fixed?

**Comment by alishaz-polymath** [comment]
> where

Slugify doesn't allow capital names, does it?

**Comment by squalou** [comment]
Hi,
just to mention that this bug still exists, I just faced it on latest build of cal.diy branch.

UI should enforce lowercase (or, any compatible) format.

Could someone confirm / reopen ? Or at least document the caveat ?
