### ISSUE TITLE
cal.com deployment redirects to localhost:3000 every time

### ISSUE THREAD

**Issue by kabilesh13** [calcom/cal.com#21921]
We have recently deployed Cal.com in our Kubernetes cluster using the Helm chart. The UI is accessible via our custom domain (https://calcom.example.com/). However, we are encountering an issue with the authentication flow.

When attempting to log in, the application redirects to http://localhost:3000 instead of maintaining the proper domain and route (e.g., https://calcom.example.com/auth/...). As a result, the login process fails.

Below are the environment variables currently configured in our deployment:

- name: NEXTAUTH_URL
          value: https://calcom.example.com

- name: NEXT_PUBLIC_API_V2_URL
          value: https://calcom.example.com/api/v2

- name: NEXT_PUBLIC_WEBAPP_URL
         value: https://calcom.example.com

We are passing all three environment variables with the custom domain as you mentioned. However, when I attempt to log in, it redirects to localhost:3000. You advised using a publicly available domain, but we have an internal domain that should be accessible from our internal network. Unfortunately, it still defaults to localhost:3000.

Could you please advise on the correct configuration for these environment variables in a server setup behind a reverse proxy or ingress controller? If there are any additional settings or known issues regarding domain handling in Kubernetes deployments, we would appreciate your guidance.

**Comment by Arindam01gi** [comment]
@kabilesh13 Can I work on this?

**Comment by kabilesh13** [comment]
@Arindam01gi  yes please, you need more input on this?

**Comment by Arindam01gi** [comment]
Hi @kabilesh13  ,
This  is my understanding. Please confirm it.

## Problem statement
We have successfully deployed Cal.com using the Helm chart and can access the UI via our custom domain, `https://calcom.example.com`.

The core problem we're observing is that during the authentication flow, after initiating a login, the application redirects the user to `http://localhost:3000` instead of maintaining the correct public domain and path (e.g., `https://calcom.example.com/auth/...`). This incorrect redirect prevents successful login.

We have configured the following environment variables in our deployment, all pointing to our custom domain:
- `NEXTAUTH_URL=https://calcom.example.com`
- `NEXT_PUBLIC_API_V2_URL=https://calcom.example.com/api/v2`
- `NEXT_PUBLIC_WEBAPP_URL=https://calcom.example.com`

## Solution

I research a bit on it. and this is what I get, The current implementation of the NextAuth.js options (in `packages/features/auth/lib/next-auth-options.ts`, via the `getOptions` function) does not set the trustHost option in the returned AuthOptions object

 
 ```
export const getOptions = ({
       getDubId,
     }: {
       getDubId: () => string | undefined;
     }): AuthOptions => ({
       // ...existing config...
       trustHost: true, // <-- Add this line
       // ...existing config...
     });

```

### Why is this important?
- When running behind a reverse proxy (like Kubernetes Ingress), NextAuth.js needs to trust the `X-Forwarded-Host` and `X-Forwarded-Proto` headers to correctly determine the public URL for redirects.
- If `trustHost` is not set to `true`, NextAuth.js may ignore these headers and fall back to defaults like localhost:3000, causing the exact issue we are experiencing.

## Question
I am not sure how to test this part with Kubernetes cluster . Can you help me with  that?

Thanks for your help!

**Comment by kabiln13** [comment]
@Arindam01gi thanks for your time on the analysis, should i pass trusthost as env variable for the deployment and share the output?

**Comment by Arindam01gi** [comment]
@kabiln13 13 Sure! Thanks.

**Comment by kabilesh13** [comment]
Hey Arindam,
I attempted to set the required environment variables as you suggested:

            - name: NEXTAUTH_URL
              value: "https://calcom.example.vite"
            - name: NEXT_PUBLIC_WEBAPP_URL
              value: "https://calcom.example.vite"
            - name: NEXT_PUBLIC_API_V2_URL
              value: "https://calcom.example.vite/api/v2"
            - name: trustHost
              value: "true"

However, I encountered an error related to the issuer certificate. I've configured the reverse proxy using ingress, and the certificate has been applied accordingly. Here's the error message:


26@calcom/web:start: Failed to load translations for en/common, falling back to English: TypeError: Fetch failed
25@calcom/web:start:     at async l (.next/server/chunks/66219.js:1:23811)
24@calcom/web:start:     at async b (.next/server/chunks/66219.js:1:59407)
23@calcom/web:start:   [cause]: [Error: Unable to get local issuer certificate] {
22@calcom/web:start:     code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
21@calcom/web:start:   }
20@calcom/web:start: }
19@calcom/web:start: Could not fetch fallback translations: TypeError: Fetch failed
18@calcom/web:start:     at async l (.next/server/chunks/66219.js:1:23811)
17@calcom/web:start:     at async b (.next/server/chunks/66219.js:1:59407)
16@calcom/web:start:   [cause]: [Error: Unable to get local issuer certificate] {
15@calcom/web:start:     code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
14@calcom/web:start:   }
13@calcom/web:start: }
12@calcom/web:start: [next-auth][error][client_fetch_error]
11@calcom/web:start: https://next-auth.js.org/errors#client_fetch_error Fetch failed {
10@calcom/web:start:   error: {
9@calcom/web:start:     message: 'Fetch failed',
8@calcom/web:start:     stack: 'TypeError: Fetch failed\n' +
7@calcom/web:start:       '    at node:internal/deps/undici/undici:12637:11\n' +
6@calcom/web:start:       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
5@calcom/web:start:     name: 'TypeError'
4@calcom/web:start:   },
3@calcom/web:start:   url: 'https://calcom.qacore.vite/api/auth/csrf',
2@calcom/web:start:   message: 'Fetch failed'
1@calcom/web:start: }

Since the communication occurs within the pod due to the reverse proxy setup, I assumed it could use localhost. I updated the environment variables, which resolved the certificate issue. However, the application still redirects to localhost when accessed through the internal network. redirection to localhost happens even when the cert issue was there

**Comment by Arindam01gi** [comment]
Hey @kabiln13 Thanks for updating. But you have to put trustHost option inside `packages/features/auth/lib/next-auth-options.ts` this file inside this function like 
```
export const getOptions = ({
      getDubId,
    }: {
      getDubId: () => string | undefined;
    }): AuthOptions => ({
      // ...existing config...
      trustHost: true, // <-- Add this line
      // ...existing config...
    });
```
Try it once . Also I'm searching for different solution. Thanks.

**Comment by kabilesh13** [comment]
Hello @Arindam01gi , currently we are using officially published docker image ver 1.0.4, you want us too try modifying the source code and build a new image to test it?

**Comment by Arindam01gi** [comment]
@kabiln13  I don't have any idea how to test this, No sure any other way to do it. Also didn't find any other proper solution that can be fruitful.

**Comment by nepomuc** [comment]
Having a similar issue: Redirect to localhost:3000 when confirming a booking request. The confirmation works successfully in the background but the redirect is to localhost:3000. I set NEXT_PUBLIC_WEBAPP_URL correctly.

**Comment by aeonoea** [comment]
I have the same issue, get redirected to localhost instead of the variables set in the .env

Is that a temporary issue with the current build? I don't remember having it with the previous version used.

**Comment by kabilesh13** [comment]
@aeonoea   can you share the version number in which you haven't faced any issues with redirection?

**Comment by aeonoea** [comment]
> [@aeonoea](https://github.com/aeonoea) can you share the version number in which you haven't faced any issues with redirection?

Not exactly, since I've always used the :latest tag but I remember it must have been 5.2.x. I'm using 5.4.6 currently, will try the one from today later.

**Comment by kabilesh13** [comment]
I tried using the 5.2.17 image version, and the redirection to localhost has been resolved. 

when I access my profile in version 5.4.x, it used to show localhost. After switching back to version 5.2.17, localhost is replaced with my custom domain (calcom.example.com).  

@Arindam01gi , there might be some hardcoding issues in the newer version, but that's just a guess.

![Image](https://github.com/user-attachments/assets/91b82308-3d43-44e6-949d-f0bb31c0edca)

**Comment by aeonoea** [comment]
@kabilesh13 Interestingly, I never had this problem in my profile, the domain (cal.domain.com) is always correctly shown.

Btw, for me reverting back to 5.2.17 didn't help... currently at 5.5.0 and still have the redirect issue.

Seems like this is not the only thread where this issue is reported: #20358

**Comment by kabilesh13** [comment]
@aeonoea  that's strange, for me 5.2.17 working absolutely fine, still in logs i see below error

@calcom/web:start: [next-auth][error][CLIENT_FETCH_ERROR]
@calcom/web:start: https://next-auth.js.org/errors#client_fetch_error fetch failed {
@calcom/web:start:   error: {
@calcom/web:start:     message: 'fetch failed',
@calcom/web:start:     stack: 'TypeError: fetch failed\n' +
@calcom/web:start:       '    at node:internal/deps/undici/undici:12637:11\n' +
@calcom/web:start:       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
@calcom/web:start:     name: 'TypeError'
@calcom/web:start:   },
@calcom/web:start:   url: 'https://calcom.qacore.com/api/auth/csrf',
@calcom/web:start:   message: 'fetch failed'
@calcom/web:start: }
@calcom/web:start: Failed to load translations for en/common, falling back to English: TypeError: fetch failed
@calcom/web:start:     at async l (.next/server/chunks/66219.js:1:23811)
@calcom/web:start:     at async x (.next/server/chunks/66219.js:1:59037) {
@calcom/web:start:   [cause]: [Error: unable to get local issuer certificate] {
@calcom/web:start:     code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
@calcom/web:start:   }
@calcom/web:start: }
@calcom/web:start: Could not fetch fallback translations: TypeError: fetch failed
@calcom/web:start:     at async l (.next/server/chunks/66219.js:1:23811)
@calcom/web:start:     at async x (.next/server/chunks/66219.js:1:59037) {
@calcom/web:start:   [cause]: [Error: unable to get local issuer certificate] {
@calcom/web:start:     code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
@calcom/web:start:   }
@calcom/web:start: }

does anyone has any idea on where to mount the issuer certificate?

**Comment by anthonytison** [comment]
Hey,

I found a little workaround for forcing my own url. I was able to make it work on the version 5.7.1.

First, i added the env variables in the docker-compose.yml file  (can also be done in the Dockerfile)
```yaml
    environment:
      - NEXT_PUBLIC_WEBAPP_URL="https://${SERVICE_HOST}"
      - BUILT_NEXT_PUBLIC_WEBAPP_URL="https://${SERVICE_HOST}"
      - NEXTAUTH_URL="https://${SERVICE_HOST}"
``` 

Then i added a RUN command in my Dockerfile (used for other goals) which will search and replace all the localhost:3000 references among the build files.

Dockerfile
```Dockerfile
FROM calcom/cal.com:v5.7.1

... 

# Replace localhost:3000 references in all relevant files
RUN find . -type f \( -name "*.js" -o -name "*.json" -o -name "*.html" -o -name "*.css" \) \
    -not -path "./node_modules/*" \
    -exec sed -i "s|http://localhost:3000|https://${SERVICE_HOST}|g" {} + && \
    find . -type f \( -name "*.js" -o -name "*.json" -o -name "*.html" -o -name "*.css" \) \
    -not -path "./node_modules/*" \
    -exec sed -i "s|localhost:3000|${SERVICE_HOST}|g" {} +

... 

CMD ["yarn", "start"]
```

As a result, the logs show me the correct url for the WEBAPP_URL. 

```bash
Match of WEBAPP_URL with ALLOWED_HOSTNAMES failed","2":{"WEBAPP_URL":"https://my-own-url.com","ALLOWED_HOSTNAMES":["https://my-own-url.com"]}
```

And the command line `printenv` on the image will also give me the right url for those env variables.

I still have the matching issue though but the redirect doesn't bother me anymore.

**Comment by mrkylegp** [comment]
> Having a similar issue: Redirect to localhost:3000 when confirming a booking request. The confirmation works successfully in the background but the redirect is to localhost:3000. I set NEXT_PUBLIC_WEBAPP_URL correctly.

Same here.

**Comment by CaliLuke** [comment]
I'm experiencing this right now, and I'm also having enormous issues building the docker. has anyone found a solution yet?

**Comment by max-carey** [comment]
We are also experiencing this issue

**Comment by shockzinfinity** [comment]
Hi! I've opened a PR that documents the solution to this issue.

The root cause is that `NEXTAUTH_URL` and `NEXT_PUBLIC_WEBAPP_URL` need to be set to the actual deployment domain. I've added a dedicated **Self-Hosting Troubleshooting Guide** that explains:
- Why the redirect to localhost happens
- The exact env vars to set (`NEXTAUTH_URL` and `NEXT_PUBLIC_WEBAPP_URL`)
- Important notes for Docker vs Vercel deployments

PR: coming shortly. Hope this helps others who run into the same issue!

**Comment by prescottmarcus76-pixel** [comment]
Hi! I've opened a PR that documents the solution to this issue.

The root cause is that NEXTAUTH_URL and NEXT_PUBLIC_WEBAPP_URL need to be
set to the actual deployment domain. I’ve added a Self-Hosting
Troubleshooting Guide that covers:

Why the redirect to localhost happens
The exact env vars to set (NEXTAUTH_URL and NEXT_PUBLIC_WEBAPP_URL)
Key differences for Docker vs Vercel deployments

PR coming shortly. Hope this helps anyone else facing the same issue!

**Comment by SeriousM** [comment]
I really don't think this is the solution.
My coolify instance is set to
```
NEXTAUTH_URL=https://${SERVICE_FQDN_CALCOM}/api/auth
NEXT_PUBLIC_WEBAPP_URL=https://${SERVICE_FQDN_CALCOM}
```
and the localhost-redirect is still happening.

Btw:
> **Note:** Failing to update `NEXT_PUBLIC_WEBAPP_URL` and `NEXTAUTH_URL` is the most common cause of redirect-to-localhost issues after deployment.

I don't think this should be in a readme in that form.
