### ISSUE TITLE
cal.com not preventing users from booking a meeting when busy

### ISSUE THREAD

**Issue by kvdb** [calcom/cal.com#5749]
### Issue Summary

I've setup cal.com with 3 calendars (1x google calendar, 2x caldav through SOGo (mailcow))

![Screenshot from 2022-11-28 21-38-07](https://user-images.githubusercontent.com/97039/204376252-afcb5ec6-9e48-4eb2-b667-66a6e64d194e.png)

If I look at my caldav, it's already having appointments at those times, (repeating events). I'd expect no options to show up for that day at all.

That leads me to believe it's not syncing properly, although I have no way of finding out how cal.com sees my combined availability.
How can I start debugging this?

**Comment by MuratDoganer** [comment]
I too have the same issue, I have Tuesdays and Thursdays blocked out in my Google Calendar as busy, but cal.com still allows bookings at those dates

Also worryingly, it does not take into account other booked meetings either, it can double book by mistake quite easily (which is a bit silly given the point of the app)

**Comment by emrysal** [comment]
Investigating this issue as part of ongoing investigation @ https://github.com/calcom/cal.com/issues/5539#issuecomment-1329332541

**Comment by gitwittidbit** [comment]
Same here. 

Connected my Apple iCloud calendars and cal.com offers time slots that are already booked in them.

**Comment by PeerRich** [comment]
@alishaz-polymath is looking into caldav issues

**Comment by gitwittidbit** [comment]
#5539 (similar issue with Round Robin meetings (whatever that is)) has been closed as fixed.

Does this mean the error we encountered is fixed, too? Has anyone tried yet?

**Comment by emrysal** [comment]
AFAIK this issue has been addressed by https://github.com/calcom/cal.com/issues/5539 - feel free to re-open if this is still happening for any of you.

**Comment by kvdb** [comment]
Related: #8516

**Comment by kvdb** [comment]
@emrysal please reopen the issue as you suggested. Things are still broken. Some more screenshots to compare a calendar from my mobile phone that works correctly (etar the open source calendar app + davx5 for syncing)

Monday 11:00-12:00 has a meeting booked (one of those recurring meetings that have perhaps been changed along the time they ran). etar/davx5 show this properly:

![shot](https://github.com/calcom/cal.com/assets/97039/c242f8ba-6b9e-470d-ae1d-56c1a0d64870) 

Gap between 11:00-12:00 because the meeting is not detected by caldav.

![Screenshot from 2024-06-09 13-28-25](https://github.com/calcom/cal.com/assets/97039/d5b13c4b-e48c-44c3-96ed-637011b6cc0d)

I'm not sure these screenshots help, but perhaps checking out how those other open source libraries manage to properly parse the recurring meetings might gain the insight that's needed.
Also gnome evolution is showing the caldav calendar properly. (no screenshot of this)
