### ISSUE TITLE
[CAL-1689] Availability & scheduling time options are not accurate for 45 min meetings

### ISSUE THREAD

**Issue by jacobzukerman** [calcom/cal.com#7547]
If you have a 45-min event, the last availability time option can often be inaccurate when scheduling. Say the host availability is 2 - 3:30 PM, and the event is set at 30-minute intervals. When scheduling the event, Cal will give users 3 PM as the last option, but that will end the meeting at 3:45 PM, 15 minutes past the host's availability. When the user attempts to schedule the 3 PM option, the booking will fail the majority of the time. 
- Sometimes, it weirdly successfully schedules (you'll see in the video)
- I don't know if the same can happen in other circumstances (30 min meetings at 15 min intervals, etc.)  

Loom walkthrough of the issue
https://www.loom.com/share/741e8991f9ca4b0daf216e419407c3a5

Steps to Reproduce:
1. Create a 45 min meeting with 30 min intervals
2. Have availability setup where a 45 min would go 15 minutes past the half or top of the hour 
3. Try to schedule. (1) see if the times are correct (2) see if the last slot fails to book

Technical details:
- Google Chrome
- Google Calendar
- v.2.6.6-sh-ce
- Self-hosted, but we can replicate this issue on app.cal.com

<sub>[CAL-1689](https://linear.app/calcom/issue/CAL-1689/availability-and-scheduling-time-options-are-not-accurate-for-45-min)</sub>

**Comment by Hybes** [comment]
I just loaded up Github to create this exact issue! I had it happen earlier.

**Comment by Hybes** [comment]
i've genuinely just made an alternative availability to workaround this for now

**Comment by jacobzukerman** [comment]
@Hybes, unfortunately, we have over 75 hosts with fairly complex schedules and availability setups. Managing workarounds for everyone has not been an option for our operations team. We added some extra error logging to know when a booking fails and a support email to help those users manually when they hit the issue.

**Comment by Hybes** [comment]
gosh, not quite so simple as mine then :)
hopefully @PeerRich or @zomars can allocate someone to work on this.

**Comment by emrysal** [comment]
Hi @jacobzukerman - oh! I see, yeah this wouldn't have been addressed as part of the DST fixings and my apologies you are experiencing this. I was unaware this issue existed - will look into it and PR ASAP

**Comment by Hybes** [comment]
@emrysal has there been any movement on this?

**Comment by PeerRich** [comment]
i believe a new version went live today that may fix this. can you try and check?

**Comment by Hybes** [comment]
@PeerRich nope, still broken
![image](https://user-images.githubusercontent.com/53020786/224418129-02583ed0-61e2-4960-8186-05d21f1cf885.png)
![image](https://user-images.githubusercontent.com/53020786/224418155-3080a878-0c2a-4ea2-a8d2-69b2dca5d798.png)

**Comment by PeerRich** [comment]
i am pretty sure this has been fixed. can you try again?
